[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
target-version = ["py37"]
line-length = 120

[tool.mypy]
python_version = "3.7"
strict = true
pretty = true
